{% set name = "PyPDF2" %}
{% set version = "3.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/PyPDF2-{{ version }}.tar.gz
  sha256: a74408f69ba6271f71b9352ef4ed03dc53a31aa404d29b5d31f53bfecfee1440

build:
  skip: true  # [py2k]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python 3.8
    - flit-core >=3.2,<4
    - pip
  run:
    - python 3.8
    - typing_extensions >=3.10.0.0  # [py<310]
    - dataclasses  # [py<37]

test:
  imports:
    - PyPDF2
  commands:
    - pip check
  requires:
    - pip

about:
  summary: A pure-python PDF library capable of splitting, merging, cropping, and transforming PDF files
  dev_url: https://github.com/py-pdf/PyPDF2
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sathomas
